sudo: required
language: generic

services:
  - docker

before_install: # If you have more than one image to test, build them all at this module.
  - docker build -t ht/docker-react -f ./client/Dockerfile.dev ./client

script: # If you have more than one image to test, write all the scripts here.
  - docker run -e CI=true ht/docker-react npm run test

after_success:
  - docker build -t htiian/multi-client ./client
  - docker build -t htiian/multi-nginx ./nginx
  - docker build -t htiian/multi-server ./server
  - docker build -t htiian/multi-worker ./worker

  # Log in to the Docker using CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

  # Once logged in, push the above built images to Docker Hub
  - docker push htiian/multi-client
  - docker push htiian/multi-nginx
  - docker push htiian/multi-server
  - docker push htiian/multi-worker
  